version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
  redis:
    image: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - '.:/data'
  sidekiq:
    depends_on:
      - 'database'
      - 'redis'
    build: .
    command: bundle exec sidekiq config/sidekiq.yml
    volumes:
      - '.:/app'
      - '/app/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
  application:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
        - NODE_ENV=development
    ports:
      - '3000:3000'
      - '3009:3009'
    volumes:
      - ./:/app
    depends_on:
      - database
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
volumes:
  redis:
  postgres:
